<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResidentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('residents')->insert([
            [
                'id' => 1,
                'household_id' => 1,
                'full_name' => 'Nguyễn Văn B',
                'gender' => 'Nam',
                'date_of_birth' => '1990-05-15',
                'place_of_birth' => 'Hà Nội',
                'ethnicity' => 'Kinh',
                'occupation' => 'Công nhân',
                'id_card_number' => '123456789',
                'date_of_issue' => '2010-01-01',
                'place_of_issue' => 'Hà Nội',
                'current_address' => 'Số nhà 2, Đường XYZ, Quận ABC',
                'previous_address' => 'Số nhà 3, Đường XYZ, Quận DEF',
                'relationship_with_head' => 'Con',
            ],
            [
                'id' => 2,
                'household_id' => 1,
                'full_name' => 'Nguyễn Thị B',
                'gender' => 'Nữ',
                'date_of_birth' => '1990-05-15',
                'place_of_birth' => 'Hà Nội',
                'ethnicity' => 'Kinh',
                'occupation' => 'Giáo viên',
                'id_card_number' => '123456789',
                'date_of_issue' => '2010-01-01',
                'place_of_issue' => 'Hà Nội',
                'current_address' => '123 Đường ABC, Quận XYZ, TP HCM',
                'previous_address' => '456 Đường DEF, Quận XYZ, TP HCM',
                'relationship_with_head' => 'Vợ',
            ],
            [
                'id' => 3,
                'household_id' => 2,
                'full_name' => 'Trần Văn C',
                'gender' => 'Nam',
                'date_of_birth' => '1985-10-20',
                'place_of_birth' => 'Hải Phòng',
                'ethnicity' => 'Kinh',
                'occupation' => 'Kỹ sư',
                'id_card_number' => '987654321',
                'date_of_issue' => '2008-06-01',
                'place_of_issue' => 'Hải Phòng',
                'current_address' => '789 Đường GHI, Quận JKL, TP HCM',
                'previous_address' => '321 Đường MNO, Quận JKL, TP HCM',
                'relationship_with_head' => 'Chồng',
            ],
            [
                'id' => 4,
                'household_id' => 2,
                'full_name' => 'Phạm Thị D',
                'gender' => 'Nữ',
                'date_of_birth' => '1992-08-10',
                'place_of_birth' => 'Hà Nội',
                'ethnicity' => 'Kinh',
                'occupation' => 'Kế toán',
                'id_card_number' => '543216789',
                'date_of_issue' => '2012-03-01',
                'place_of_issue' => 'Hà Nội',
                'current_address' => '789 Đường GHI, Quận JKL, TP HCM',
                'previous_address' => '321 Đường MNO, Quận JKL, TP HCM',
                'relationship_with_head' => 'Con',
            ],
            [
                'id' => 5,
                'household_id' => 3,
                'full_name' => 'Lê Văn E',
                'gender' => 'Nam',
                'date_of_birth' => '1998-12-05',
                'place_of_birth' => 'Hồ Chí Minh',
                'ethnicity' => 'Kinh',
                'occupation' => 'Sinh viên',
                'id_card_number' => '987654321',
                'date_of_issue' => '2018-07-01',
                'place_of_issue' => 'Hồ Chí Minh',
                'current_address' => '123 Đường PQR, Quận STU, TP HCM',
                'previous_address' => '456 Đường VWX, Quận STU, TP HCM',
                'relationship_with_head' => 'Con',
            ],
            [
                'id' => 6,
                'household_id' => 3,
                'full_name' => 'Hoàng Thị F',
                'gender' => 'Nữ',
                'date_of_birth' => '1995-03-22',
                'place_of_birth' => 'Hà Nội',
                'ethnicity' => 'Kinh',
                'occupation' => 'Nhân viên văn phòng',
                'id_card_number' => '123459876',
                'date_of_issue' => '2015-09-01',
                'place_of_issue' => 'Hà Nội',
                'current_address' => '123 Đường PQR, Quận STU, TP HCM',
                'previous_address' => '456 Đường VWX, Quận STU, TP HCM',
                'relationship_with_head' => 'Con',
            ],
            [
                'id' => 7,
                'household_id' => 4,
                'full_name' => 'Nguyễn Văn G',
                'gender' => 'Nam',
                'date_of_birth' => '1978-06-12',
                'place_of_birth' => 'Hà Nội',
                'ethnicity' => 'Kinh',
                'occupation' => 'Kỹ sư',
                'id_card_number' => '567891234',
                'date_of_issue' => '2000-05-01',
                'place_of_issue' => 'Hà Nội',
                'current_address' => '789 Đường HIJ, Quận KLM, TP HCM',
                'previous_address' => '321 Đường NOP, Quận KLM, TP HCM',
                'relationship_with_head' => 'Chồng',
            ],
            [
                'id' => 8,
                'household_id' => 4,
                'full_name' => 'Trần Thị H',
                'gender' => 'Nữ',
                'date_of_birth' => '1980-09-18',
                'place_of_birth' => 'Hồ Chí Minh',
                'ethnicity' => 'Kinh',
                'occupation' => 'Giáo viên',
                'id_card_number' => '234567891',
                'date_of_issue' => '2005-02-01',
                'place_of_issue' => 'Hồ Chí Minh',
                'current_address' => '789 Đường HIJ, Quận KLM, TP HCM',
                'previous_address' => '321 Đường NOP, Quận KLM, TP HCM',
                'relationship_with_head' => 'Vợ',
            ],
            [
                'id' => 9,
                'household_id' => 5,
                'full_name' => 'Phạm Văn I',
                'gender' => 'Nam',
                'date_of_birth' => '1994-11-25',
                'place_of_birth' => 'Hà Nội',
                'ethnicity' => 'Kinh',
                'occupation' => 'Kỹ sư',
                'id_card_number' => '789123456',
                'date_of_issue' => '2014-04-01',
                'place_of_issue' => 'Hà Nội',
                'current_address' => '123 Đường XYZ, Quận ABC, TP HCM',
                'previous_address' => '456 Đường EFG, Quận ABC, TP HCM',
                'relationship_with_head' => 'Con',
            ],
            [
                'id' => 10,
                'household_id' => 5,
                'full_name' => 'Lê Thị J',
                'gender' => 'Nữ',
                'date_of_birth' => '1996-07-08',
                'place_of_birth' => 'Hồ Chí Minh',
                'ethnicity' => 'Kinh',
                'occupation' => 'Sinh viên',
                'id_card_number' => '987123456',
                'date_of_issue' => '2016-11-01',
                'place_of_issue' => 'Hồ Chí Minh',
                'current_address' => '123 Đường XYZ, Quận ABC, TP HCM',
                'previous_address' => '456 Đường EFG, Quận ABC, TP HCM',
                'relationship_with_head' => 'Con',
            ],
        ]);
    }
}
